FROM debian:bookworm-slim AS builder


RUN apt update && apt install -y \
    python3 python3-pip \
    openjdk-17-jdk \
    jp2a \
    pillow \
    bash \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build


COPY . .


RUN javac *.java || true


FROM debian:bookworm-slim

RUN apt update && apt install -y \
    python3 \
    openjdk-17-jre \
    jp2a \
    bash \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY --from=builder /build /app


ENTRYPOINT ["bash", "/app/start.sh"]
